### ISSUE TITLE
Create Initial README

### ISSUE THREAD

**Issue by jmziya** [Greanz/kkphpframework#1]
Have an initial README with basic instructions on how to get the framework running or creating an app with it.

An example layout could be like below. Don't mind the commands;

# Requirements

> PHP x.x.x

# Create App
````
kkphpframework new myapp
`````

# Install App Dependencies
> npm install
> composer install

# Run app
`````
kkphpframework serve
`````

**Comment by jmziya** [comment]
I would love to try this framework. @Greanz , will try it out.

**Comment by Aaron-the-iam** [comment]
Anyone who tried it out
